name: Winslow Test
favicon: null
layout_spectrum: 0.7647754475474358
typography_spectrum: 0.034320385893806815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c1800'
    - '#feffd7'
    - '#e1a22e'
    - '#c7740a'
    - '#9d0301'
  brandStrength: 0.9462174249347299
  lightness: 0.22565618762746453
  saturation: 0.6752351063769311
  rhythmicContrast: 0.4938409572932869
purpose: []
