name: Winslow Test
favicon: null
layout_spectrum: 0.98418
typography_spectrum: 0.4884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#181818'
    - '#f83543'
    - '#ff6678'
    - '#8c7fb7'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
