name: Winslow Test
favicon: null
layout_spectrum: 0.98418
typography_spectrum: 0.4884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9b79c5'
    - '#01005d'
    - '#c63651'
    - '#f9ab02'
    - '#048ad0'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
